---
# tasks file for javarole

    - name:  install epel-release
      ansible.builtin.yum: 
        name: epel-release
        state: present   
      when: ansible_facts['distribution'] == "Centos"  
    - name: update cache 
      ansible.builtin.yum: 
        update_cache: yes
      when: ansible_facts['distribution'] == "Centos"
    - name: update cache 
      ansible.builtin.apt: 
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"        
    - name:  install nodejs
      ansible.builtin.package: 
        name: nodejs
        state: present 
    - name:  install npm
      ansible.builtin.package: 
        name: npm
        state: present         
